services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm run dev
    ports:
      - 3000:3000

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    # volumes:
    #   - pgadmin:/var/lib/pgadmin
    volumes:
      - data:/var/lib/pgadmin

  # bot:
  #   image: python:latest
  #   volumes:
  #     - ./discordbot:/scripts
  #   working_dir: /scripts
  #   command: python script.py

volumes:
  data:
  # pgadmin:
